name: live_object_detection_ssd_mobilenet
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  tflite_flutter:
    path: ./flutter-tflite
  camera: ^0.10.5+2
  image: ^4.0.17
  path_provider: ^2.0.15
  image_picker: ^1.0.0
  exif: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
 