

name: flutter-tflite

repository: https://github.com/tensorflow/flutter-tflite

packages:
  - .
  - example/**

command:
  version:
    branch: main
    linkToCommits: true
    workspaceChangelog: true

scripts:
  ffigen:
    name: ffigen
    description: Call ffigen and generate bindings for `src/tensorflow_lite/c_api.h`.
    run: flutter pub run ffigen --config ffigen_tensorflow_lite.yaml