

name: tflite_flutter
description: TensorFlow Lite Flutter plugin provides an easy, flexible, and fast Dart API to integrate TFLite models in flutter apps across mobile and desktop platforms.
version: 0.11.0
homepage: https://github.com/tensorflow/flutter-tflite

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.2
  plugin_platform_interface: ^2.0.2
  quiver: ^3.0.0
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^10.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  melos: ^6.1.0
  test: ^1.6.4

flutter:

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos: 
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true


